<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Pek.NAI.Benchmark</AssemblyName>
    <RootNamespace>Pek.NAI.Benchmark</RootNamespace>
    <Optimize>true</Optimize>
    <!-- 基准项目不参与打包与发布流程 -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pek.NAI\Pek.NAI.csproj" />
  </ItemGroup>
</Project>
