<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net11.0</TargetFrameworks>
    <OutputPath>..\Bin\Test</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NCore" Version="4.25.2026.911-beta0202" />
    <PackageReference Include="DH.NStardust.Extensions" Version="4.25.2026.914-beta0858" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\XUnitTest\Helpers\DashScopeKeyLoader.cs" Link="Helpers\DashScopeKeyLoader.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pek.NAI\Pek.NAI.csproj" />
  </ItemGroup>

</Project>
